// 假数据 - 展示UI用，后续替换为真实 API

import { Article, ArticleCategory } from "./types";

export const dummyCategories: ArticleCategory[] = [
  { id: "beginner", name: "新手入门", slug: "beginner", count: 12 },
  { id: "security", name: "安全指南", slug: "security", count: 8 },
  { id: "trading", name: "交易技巧", slug: "trading", count: 15 },
  { id: "wallet", name: "钱包教程", slug: "wallet", count: 6 },
  { id: "defi", name: "DeFi 探索", slug: "defi", count: 10 },
  { id: "news", name: "行业动态", slug: "news", count: 20 },
];

export const dummyArticles: Article[] = [
  {
    id: 1,
    title: "比特币新手完全指南：从零开始了解BTC",
    description: "全面介绍比特币的基本概念、工作原理、如何购买以及安全存储方法。适合完全没有接触过加密货币的新手阅读，本文将带你从零开始系统了解比特币的方方面面，包括挖矿原理、交易机制、钱包类型选择等核心知识，让你在进入币圈之前打下坚实的理论基础。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "加密小白", avatar: "" },
    coverImage: "",
    category: "新手入门",
    tags: ["比特币", "入门教程", "区块链"],
    publishDate: "2024-10-15T10:00:00Z",
    readTime: 8,
    views: 1250,
    featured: true,
    slug: "bitcoin-beginner-guide",
  },
  {
    id: 2,
    title: "如何保护你的加密货币钱包：安全最佳实践",
    description: "详细讲解钱包安全的各个方面，包括私钥管理、双重验证、冷钱包使用等关键安全措施。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "安全专家", avatar: "" },
    coverImage: "",
    category: "安全指南",
    tags: ["钱包安全", "私钥", "冷钱包"],
    publishDate: "2024-10-12T14:30:00Z",
    readTime: 12,
    views: 980,
    featured: true,
    slug: "wallet-security-best-practices",
  },
  {
    id: 3,
    title: "现货交易 vs 合约交易：新手该如何选择？",
    description: "对比现货和合约交易的区别、风险和收益特点，帮助新手找到适合自己的交易方式。本文详细分析两种交易方式的优缺点。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "交易达人", avatar: "" },
    coverImage: "",
    category: "交易技巧",
    tags: ["现货", "合约", "交易策略"],
    publishDate: "2024-10-10T09:15:00Z",
    readTime: 10,
    views: 1560,
    featured: false,
    slug: "spot-vs-futures-trading",
  },
  {
    id: 4,
    title: "MetaMask 钱包完整使用教程",
    description: "从安装、创建钱包到连接 DApp，手把手教你使用最流行的以太坊钱包 MetaMask。无论你是 DeFi 新手还是想探索 Web3 世界，这篇教程都能帮你快速上手，掌握钱包的基本操作和高级功能。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "DeFi 玩家", avatar: "" },
    coverImage: "",
    category: "钱包教程",
    tags: ["MetaMask", "以太坊", "DApp"],
    publishDate: "2024-10-08T16:20:00Z",
    readTime: 15,
    views: 2100,
    featured: true,
    slug: "metamask-complete-guide",
  },
  {
    id: 5,
    title: "什么是 DeFi？去中心化金融入门",
    description: "深入浅出地介绍 DeFi 的概念、常见应用场景以及参与 DeFi 的注意事项。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "区块链研究员", avatar: "" },
    coverImage: "",
    category: "DeFi 探索",
    tags: ["DeFi", "去中心化", "智能合约"],
    publishDate: "2024-10-05T11:00:00Z",
    readTime: 20,
    views: 1890,
    featured: false,
    slug: "defi-introduction",
  },
  {
    id: 6,
    title: "2024年Q4加密市场趋势分析",
    description: "分析当前市场环境、监管动态、技术发展趋势，展望Q4可能的市场走向。本文基于链上数据和宏观经济指标，为投资者提供专业的市场分析和投资建议，帮助你在复杂的市场环境中把握机会、规避风险，做出更明智的投资决策。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "市场分析师", avatar: "" },
    coverImage: "",
    category: "行业动态",
    tags: ["市场分析", "趋势", "2024"],
    publishDate: "2024-10-01T08:00:00Z",
    readTime: 18,
    views: 3200,
    featured: true,
    slug: "2024-q4-market-analysis",
  },
  {
    id: 7,
    title: "如何识别和避免加密货币诈骗",
    description: "列举常见的诈骗手段，教你识别钓鱼网站、假客服、庞氏骗局等，保护资产安全。加密货币诈骗层出不穷。",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "安全专家", avatar: "" },
    coverImage: "",
    category: "安全指南",
    tags: ["诈骗防范", "钓鱼", "安全"],
    publishDate: "2024-09-28T13:45:00Z",
    readTime: 10,
    views: 1450,
    featured: false,
    slug: "avoid-crypto-scams",
  },
  {
    id: 8,
    title: "交易所提现到钱包：完整操作指南",
    description: "详细说明如何从交易所安全地提现到个人钱包，包括网络选择、地址确认等关键步骤。不懂如何提币？担心操作失误导致资产丢失？",
    content: "<p>这里是文章正文内容...</p>",
    author: { name: "加密小白", avatar: "" },
    coverImage: "",
    category: "新手入门",
    tags: ["提现", "钱包", "操作指南"],
    publishDate: "2024-09-25T10:30:00Z",
    readTime: 12,
    views: 1780,
    featured: false,
    slug: "withdraw-to-wallet-guide",
  },
];


